# Autogenerated
from .core.cim15 import *
from .core.cim15.ModelMetaData import *
from .core.cim15.ModelMetaData.ModelDescription import *
from .core.cim15.ModelMetaData.PowerSystemProject import *
from .core.cim15.ModelMetaData.ModelAuthority import *
from .core.cim15.TC57CIM import *
from .core.cim15.TC57CIM.IEC61968 import *
from .core.cim15.TC57CIM.IEC61968.InfIEC61968 import *
from .core.cim15.TC57CIM.IEC61968.InfIEC61968.InfAssets import *
from .core.cim15.TC57CIM.IEC61968.InfIEC61968.InfERPSupport import *
from .core.cim15.TC57CIM.IEC61968.InfIEC61968.InfLocations import *
from .core.cim15.TC57CIM.IEC61968.InfIEC61968.InfWork import *
from .core.cim15.TC57CIM.IEC61968.InfIEC61968.InfMetering import *
from .core.cim15.TC57CIM.IEC61968.InfIEC61968.InfMetering.ReadingTypeEnumerations import *
from .core.cim15.TC57CIM.IEC61968.InfIEC61968.InfMetering.ExistingEnumExtensions import *
from .core.cim15.TC57CIM.IEC61968.InfIEC61968.InfAssetInfo import *
from .core.cim15.TC57CIM.IEC61968.InfIEC61968.Sandbox import *
from .core.cim15.TC57CIM.IEC61968.InfIEC61968.Sandbox.InfNewAssets import *
from .core.cim15.TC57CIM.IEC61968.InfIEC61968.InfTypeAsset import *
from .core.cim15.TC57CIM.IEC61968.InfIEC61968.InfCommon import *
from .core.cim15.TC57CIM.IEC61968.InfIEC61968.InfWiresExt import *
from .core.cim15.TC57CIM.IEC61968.InfIEC61968.InfCustomers import *
from .core.cim15.TC57CIM.IEC61968.Operations import *
from .core.cim15.TC57CIM.IEC61968.Common import *
from .core.cim15.TC57CIM.IEC61968.Metering import *
from .core.cim15.TC57CIM.IEC61968.Customers import *
from .core.cim15.TC57CIM.IEC61968.AssetInfo import *
from .core.cim15.TC57CIM.IEC61968.LoadControl import *
from .core.cim15.TC57CIM.IEC61968.PaymentMetering import *
from .core.cim15.TC57CIM.IEC61968.Assets import *
from .core.cim15.TC57CIM.IEC61968.Work import *
from .core.cim15.TC57CIM.IEC62325 import *
from .core.cim15.TC57CIM.IEC62325.MarketOperations import *
from .core.cim15.TC57CIM.IEC62325.MarketOperations.MktDomain import *
from .core.cim15.TC57CIM.IEC62325.MarketOperations.MarketSystem import *
from .core.cim15.TC57CIM.IEC62325.MarketOperations.MarketSystem.ExternalInputs import *
from .core.cim15.TC57CIM.IEC62325.MarketOperations.MarketSystem.MarketResults import *
from .core.cim15.TC57CIM.IEC62325.MarketOperations.ParticipantInterfaces import *
from .core.cim15.TC57CIM.IEC62325.MarketOperations.ReferenceData import *
from .core.cim15.TC57CIM.IEC62325.MarketOperations.MarketPlan import *
from .core.cim15.TC57CIM.IEC62325.MarketOperations.MarketOpCommon import *
from .core.cim15.TC57CIM.IEC62325.MarketOperations.CongestionRevenueRights import *
from .core.cim15.TC57CIM.IEC62325.MarketOperations.MarketQualitySystem import *
from .core.cim15.TC57CIM.IEC62325.InfIEC62325 import *
from .core.cim15.TC57CIM.IEC62325.InfIEC62325.InfFinancial import *
from .core.cim15.TC57CIM.IEC62325.InfIEC62325.InfEnergyScheduling import *
from .core.cim15.TC57CIM.IEC62325.InfIEC62325.InfDomain import *
from .core.cim15.TC57CIM.IEC62325.InfIEC62325.InfExternalInputs import *
from .core.cim15.TC57CIM.IEC62325.InfIEC62325.InfMarketOperations import *
from .core.cim15.TC57CIM.IEC62325.InfIEC62325.InfMarketResults import *
from .core.cim15.TC57CIM.IEC62325.InfIEC62325.InfCongestionRevenueRights import *
from .core.cim15.TC57CIM.IEC62325.InfIEC62325.InfReservation import *
from .core.cim15.TC57CIM.IEC62325.InfIEC62325.InfParticipantInterfaces import *
from .core.cim15.TC57CIM.IEC62325.MarketManagement import *
from .core.cim15.TC57CIM.IEC62325.MarketCommon import *
from .core.cim15.TC57CIM.IEC61970 import *
from .core.cim15.TC57CIM.IEC61970.InfIEC61970 import *
from .core.cim15.TC57CIM.IEC61970.InfIEC61970.InfSIPS import *
from .core.cim15.TC57CIM.IEC61970.InfIEC61970.ICCP import *
from .core.cim15.TC57CIM.IEC61970.InfIEC61970.InfOperationalLimits import *
from .core.cim15.TC57CIM.IEC61970.InfIEC61970.InfEnergySource import *
from .core.cim15.TC57CIM.IEC61970.Base import *
from .core.cim15.TC57CIM.IEC61970.Base.OperationalLimits import *
from .core.cim15.TC57CIM.IEC61970.Base.Protection import *
from .core.cim15.TC57CIM.IEC61970.Base.Core import *
from .core.cim15.TC57CIM.IEC61970.Base.Meas import *
from .core.cim15.TC57CIM.IEC61970.Base.Generation import *
from .core.cim15.TC57CIM.IEC61970.Base.Generation.GenerationTrainingSimulation import *
from .core.cim15.TC57CIM.IEC61970.Base.Generation.Production import *
from .core.cim15.TC57CIM.IEC61970.Base.DC import *
from .core.cim15.TC57CIM.IEC61970.Base.Wires import *
from .core.cim15.TC57CIM.IEC61970.Base.LoadModel import *
from .core.cim15.TC57CIM.IEC61970.Base.Faults import *
from .core.cim15.TC57CIM.IEC61970.Base.StateVariables import *
from .core.cim15.TC57CIM.IEC61970.Base.SCADA import *
from .core.cim15.TC57CIM.IEC61970.Base.Domain import *
from .core.cim15.TC57CIM.IEC61970.Base.AuxiliaryEquipment import *
from .core.cim15.TC57CIM.IEC61970.Base.DiagramLayout import *
from .core.cim15.TC57CIM.IEC61970.Base.ControlArea import *
from .core.cim15.TC57CIM.IEC61970.Base.Equivalents import *
from .core.cim15.TC57CIM.IEC61970.Base.Topology import *
from .core.cim15.TC57CIM.IEC61970.Base.Contingency import *
from .core.cim15.TC57CIM.IEC61970.Dynamics import *
from .core.cim15.TC57CIM.IEC61970.Dynamics.StandardModels import *
from .core.cim15.TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics import *
from .core.cim15.TC57CIM.IEC61970.Dynamics.StandardModels.ExcitationSystemDynamics import *
from .core.cim15.TC57CIM.IEC61970.Dynamics.StandardModels.AsynchronousMachineDynamics import *
from .core.cim15.TC57CIM.IEC61970.Dynamics.StandardModels.PFVArControllerType1Dynamics import *
from .core.cim15.TC57CIM.IEC61970.Dynamics.StandardModels.LoadDynamics import *
from .core.cim15.TC57CIM.IEC61970.Dynamics.StandardModels.TurbineGovernorDynamics import *
from .core.cim15.TC57CIM.IEC61970.Dynamics.StandardModels.SynchronousMachineDynamics import *
from .core.cim15.TC57CIM.IEC61970.Dynamics.StandardModels.VoltageAdjusterDynamics import *
from .core.cim15.TC57CIM.IEC61970.Dynamics.StandardModels.PowerSystemStabilizerDynamics import *
from .core.cim15.TC57CIM.IEC61970.Dynamics.StandardModels.OverexcitationLimiterDynamics import *
from .core.cim15.TC57CIM.IEC61970.Dynamics.StandardModels.UnderexcitationLimiterDynamics import *
from .core.cim15.TC57CIM.IEC61970.Dynamics.StandardModels.VoltageCompensatorDynamics import *
from .core.cim15.TC57CIM.IEC61970.Dynamics.StandardModels.PFVArControllerType2Dynamics import *
from .core.cim15.TC57CIM.IEC61970.Dynamics.StandardModels.DiscontinuousExcitationControlDynamics import *
from .core.cim15.TC57CIM.IEC61970.Dynamics.StandardModels.MechanicalLoadDynamics import *
from .core.cim15.TC57CIM.IEC61970.Dynamics.StandardModels.TurbineLoadControllerDynamics import *
from .core.cim15.TC57CIM.IEC61970.Dynamics.UserDefinedModels import *
from .core.cim15.TC57CIM.IEC61970.Dynamics.StandardInterconnections import *
from .core.cim15.TC57CIM.PackageDependencies import *


def fuzzy_find(query):
    clsmembers = get_clsmembers()

    from fuzzywuzzy import process

    return [clsmembers[name] for name, percent in process.extract(query, clsmembers.keys())]


def get_clsmembers():
    import sys
    import inspect
    clsmembers = {name: cls for name, cls in inspect.getmembers(sys.modules[__name__], inspect.isclass)}
    return clsmembers
